---
# tasks file for docker-compose

- name: "Downloading and placing {{ dockercompose_app }} {{ dockercompose_version }} to {{ dockercompose_bin_path }} on Debian based systems"
  get_url:
    url: "{{ dockercompose_dl_url }}"
    dest: "{{ dockercompose_bin_path }}/{{ dockercompose_app }}"
    mode: "{{ dockercompose_file_mode }}"
